apiVersion: apps/v1
kind: Deployment
metadata:
  name: Mavenbuild
  labels:
    app: 
spec:
  selector:
    matchLabels:
      app: Mavenbuild
  template:
    metadata:
      labels:
        app: Mavenbuild
    spec:
      containers:
      - image: vinutha25/Mavenbuild
        name: Mavenbuild
        ports:
        - containerPort: 8081
          name: Mavenbuild
